### ISSUE TITLE
Popup window is opened in chrome browser when routing in sample application

### ISSUE THREAD

**Issue by tsampath** [Azure-Samples/active-directory-b2c-javascript-angular-spa#22]
## Library
active-directory-b2c-javascript-angular-spa
## Description

When I tested this sample, I found that when clicking "Call API", it opens the browser pop up in Chrome browser. This is happened when routing to Profile components and not when calling an API.  Same behavior is encountered with your test B2C environment as well as our environment. Pop up is not opened in Edge browser, but it seems it is happening in background. 

Could someone  please let me know the reason for this and how to avoid it?

Thanks,
Thushara

**Comment by derisen** [comment]
@tsampath this is likely caused by an issue with retrieving the token from cache, a regression from the last msal.js update. Updating [msal.js to 1.4.1](https://github.com/AzureAD/microsoft-authentication-library-for-js/releases/tag/msal-v1.4.1) should resolve it (we will soon update the sample as well).
