### ISSUE TITLE
Error when acquiring token for scopes

### ISSUE THREAD

**Issue by andrewcrayden** [Azure-Samples/active-directory-b2c-javascript-angular-spa#4]
This sample app is really good for getting up and running with Angular and AD B2C. However when moving the "Call API" logic to a component other than the home component, the following error is returned:

"Error when acquiring token for scopes: https://myazurefunction.onmicrosoft.com/api/demo.read ServerError: AADB2C90006: The redirect URI 'http://localhost:4200/dashboard' provided in the request is not registered for the client id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'."

The dashboard component is a bit different because it is calling an Azure Function instead of the default API. The Azure function is protected by Azure AD B2C, and only allows requests that have been authenticated. When adding the dashboard route to the Redirect URIs configuration for testing, the API call works. But it is unreasonable to add every single application route to this configuration.

How can the Angular application call the API from any component/route, without having to add every route to the Redirect URIs configuration?

```
import { Component, OnInit } from '@angular/core';
import { BroadcastService, MsalService} from '@azure/msal-angular';
import { HttpClient } from '@angular/common/http';
import { tokenRequest, isIE } from '../../../config';
import { apiConfig } from '../../../config';

@Component({
  selector: 'dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  loggedIn = false;
  tokenAcquired = false;
  apiResponse: any;

  constructor(private broadcastService: BroadcastService, private authService: MsalService, private http: HttpClient) { }

  ngOnInit() {
    this.checkAccount();

    this.broadcastService.subscribe('msal:loginSuccess', (payload) => {
      this.checkAccount();
    });

    this.broadcastService.subscribe('msal:acquireTokenSuccess', (payload) => {
      console.log('access token acquired: ' + new Date().toString());
      this.tokenAcquired = true;
    });
 
    this.broadcastService.subscribe('msal:acquireTokenFailure', (payload) => {
      console.log('access token acquisition fails');
      this.tokenAcquired = false;
    });

    // redirect callback for redirect flow (IE)
    this.authService.handleRedirectCallback((authError, response) => {
      if (authError) {
        console.error('Redirect Error: ', authError.errorMessage);
        return;
      }

      console.log('Redirect Success: ', response.accessToken);
      this.tokenAcquired = true;
    });
  }

  // other methods
  checkAccount() {
    this.loggedIn = !!this.authService.getAccount();
  }

  getProfile() {
    if (isIE) {
      this.authService.loginRedirect(tokenRequest);
    } else {
      this.callAPI();
    }
  }

  callAPI() {
    console.log('API call made at: ' + new Date().toString());

    this.http.get("https://myazurefunction.azurewebsites.net/api/Function1").toPromise()
      .then(res => {
        this.apiResponse = res;
        console.log('API responded at: ' + new Date().toString());
        console.log(this.apiResponse.toString());
      }).catch(err => console.log(err));
  }

}
```

**Comment by derisen** [comment]
The `redirectUri` is used to provide a trusted destination for Azure AD to send the security tokens. Once your application obtains a security token, `MSAL Http Interceptor` takes care of attaching it to the API calls to coordinates you provide in `ProtectedResourceMap` (in `app-config.ts`). If a resource is defined in `ProtectedResourceMap` but the user tries to call it before authentication, `MSALGuard` will trigger authentication first (in `app-routing.module.ts` -I have made some improvements on the sample but they are not merged yet, can you take a look at the `derisen` branch?)

With respect to your case here, indeed you don't have to register every component/route to call an API. Once your app gets the tokens after authentication (through the registered `redirectUri`) it is up to your application to redirect the user wherever you need them. There are different ways to do this: one way is to configure your router so that it would detect when the user authenticates and redirects them afterwards. You can use a `state` parameter for that. See the discussion [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/reply-url) (and check the msal.js authentication parameters [here](https://azuread.github.io/microsoft-authentication-library-for-js/docs/msal/modules/_authenticationparameters_.html)).


```
 getProfile() {
    if (isIE) {
      this.authService.loginRedirect(tokenRequest);
    } else {
      this.callAPI();
    }
  }
```

This part looks strange. It seems like if a user clicks on getProfile(), your app would try to call the API without authentication.

**Comment by andrewcrayden** [comment]
Thank you for the response.

The Redirect URI that I am using in the B2C `webapi` application is `http://localhost:4200`.

The reason I tried changing the `getProfile` method is that it is an awkward user experience for a user to see a popup on every API call. The code has been changed mostly back to what you have, but it is still returning the exact same error. The authservice seems to not be providing the token. It does work if I add the route to the Redirect URI configuration.

What am I missing?

## dashboard.component.ts
```
getProfile() {
    if (isIE) {
      this.authService.loginRedirect(tokenRequest);
    } else {
      this.authService.loginPopup(tokenRequest)
        .then(res => {
          this.callAPI(apiConfig.webApi);
        })
        .catch(err => console.log(err));
    }
  }

  callAPI(url: string) {
    console.log('API call made at: ' + new Date().toString());

    this.http.get(url + "/Function1").toPromise()
      .then(res => {
        this.apiResponse = res;
        console.log('API responded at: ' + new Date().toString());
        console.log(this.apiResponse.toString());
      }).catch(err => console.log(err));
  }
```

**Comment by andrewcrayden** [comment]
Just tried the `derisen` branch. Looks like any route works with no need for a popup due to good use of the `ngOnInit` method. Thanks again for the support, hoping that this sample will be continuously improved by yourself and Microsoft.

**Comment by derisen** [comment]
no worries : ) I'll try to merge these changes as soon as I can.
